### ISSUE TITLE
A dangling layer in forward call?

### ISSUE THREAD

**Issue by InnovArul** [lafith/Mobile-UNet#1]
Just came across this implementation and noticed the usage of a non-registered (dangling) layer in InvertedResidualBlock's forward call.
When this line is executed, a new conv layer will be created every time & it won't be trained by the optimizer. 
Is it for any particular usecase? 

https://github.com/lafith/Mobile-UNet/blob/50e159d8f39bd8300610629d0e26f4ab3b96bd72/model.py#L58-L60

**Comment by lafith** [comment]
@InnovArul  Thank you for pointing it out. I have fixed it in the latest commit.
